draw_config:
  key_w: 60.0
  key_h: 56.0
  split_gap: 30.0
  combo_w: 18.0
  combo_h: 16.0
  key_rx: 6.0
  key_ry: 6.0
  dark_mode: false
  n_columns: 1
  separate_combo_diagrams: false
  combo_diagrams_scale: 2
  inner_pad_w: 2.0
  inner_pad_h: 2.0
  outer_pad_w: 30.0
  outer_pad_h: 56.0
  line_spacing: 1.2
  arc_radius: 6.0
  append_colon_to_layer_header: true
  small_pad: 2.0
  legend_rel_x: 0.0
  legend_rel_y: 0.0
  draw_key_sides: false
  key_side_pars:
    rel_x: 0
    rel_y: 4
    rel_w: 12
    rel_h: 12
    rx: 4
    ry: 4
  svg_extra_style: ''
  footer_text: Created with <a href="https://github.com/caksoylar/keymap-drawer">keymap-drawer</a>
  shrink_wide_legends: 7
  style_layer_activators: true
  glyph_tap_size: 14
  glyph_hold_size: 12
  glyph_shifted_size: 10
  glyphs: {}
parse_config:
  preprocess: true
  skip_binding_parsing: false
  raw_binding_map:
    '&mkp LCLK': $$mdi:cursor-default-click$$
    '&mkp RCLK': $$mdi:cursor-default-click-outline$$
    '&msc SCRL_UP': '$$mdi:mouse-move-up$$'
    '&msc SCRL_DOWN': '$$mdi:mouse-move-down$$'
    '&mmv MOVE_LEFT':
      tap:     $$mdi:tortoise$$
      shifted: $$mdi:arrow-left$$
      type:    sym_by_sym
    '&mmv MOVE_RIGHT':
      tap:     $$mdi:tortoise$$
      shifted: $$mdi:arrow-right$$
      type:    sym_by_sym
    '&mmv MOVE_UP':
      tap:     $$mdi:tortoise$$
      shifted: $$mdi:arrow-up$$
      type:    sym_by_sym
    '&mmv MOVE_DOWN':
      tap:     $$mdi:tortoise$$
      shifted: $$mdi:arrow-down$$
      type:    sym_by_sym
    '&fmmv MOVE_LEFT':
      tap:     $$mdi:mouse$$
      shifted: $$mdi:arrow-left$$
      type:    sym_by_sym
    '&fmmv MOVE_RIGHT':
      tap:     $$mdi:mouse$$
      shifted: $$mdi:arrow-right$$
      type:    sym_by_sym
    '&fmmv MOVE_UP':
      tap:     $$mdi:mouse$$
      shifted: $$mdi:arrow-up$$
      type:    sym_by_sym
    '&fmmv MOVE_DOWN':
      tap:     $$mdi:mouse$$
      shifted: $$mdi:arrow-down$$
      type:    sym_by_sym
    '&out OUT_BLE':
      tap: $$mdi:keyboard$$
      shifted: $$mdi:bluetooth$$
      type: sym_by_sym
    '&out OUT_USB':
      tap: $$mdi:keyboard$$
      shifted: $$mdi:usb$$
      type: sym_by_sym
    '&out OUT_TOG':
      tap: $$mdi:toggle-switch$$
      hold: $$mdi:bluetooth$$
      shifted: $$mdi:usb$$
      type: toggle
    '&bt BT_CLR':
      tap: $$mdi:bluetooth-settings$$
      shifted: $$mdi:close-thick$$
      type: sym_sub_text
    '&bt BT_CLR_ALL':
      tap: $$mdi:bluetooth-settings$$
      shifted: $$mdi:close-thick$$
      hold: $$mdi:asterisk$$
      type: sym_sub_text
    '&bt BT_SEL 0':
      tap: $$mdi:bluetooth-connect$$
      shifted: '0'
      type: sym_sub_text
    '&bt BT_SEL 1':
      tap: $$mdi:bluetooth-connect$$
      shifted: '1'
      type: sym_sub_text
    '&bt BT_SEL 2':
      tap: $$mdi:bluetooth-connect$$
      shifted: '2'
      type: sym_sub_text
    '&bt BT_SEL 3':
      tap: $$mdi:bluetooth-connect$$
      shifted: '3'
      type: sym_sub_text
    '&bt BT_SEL 4':
      tap: $$mdi:bluetooth-connect$$
      shifted: '4'
      type: sym_sub_text
    '&bt BT_DISC 0':
      tap: $$mdi:bluetooth-off$$
      shifted: '0'
      type: sym_sub_text
    '&bt BT_DISC 1':
      tap: $$mdi:bluetooth-off$$
      shifted: '1'
      type: sym_sub_text
    '&bt BT_DISC 2':
      tap: $$mdi:bluetooth-off$$
      shifted: '2'
      type: sym_sub_text
    '&bt BT_DISC 3':
      tap: $$mdi:bluetooth-off$$
      shifted: '3'
      type: sym_sub_text
    '&bt BT_DISC 4':
      tap: $$mdi:bluetooth-off$$
      shifted: '4'
      type: sym_sub_text
    '&bt BT_PRV':
      tap: $$mdi:bluetooth$$
      shifted: $$mdi:skip-previous$$
      type: sym_sub_text
    '&bt BT_NXT':
      tap: $$mdi:bluetooth$$
      shifted: $$mdi:skip-next$$
      type: sym_sub_text
    '&dis_down':
      tap:     '$$tablerf:brand-discord$$'
      shifted: $$mdi:arrow-down$$
      type:    sym_by_sym
    '&dis_up':
      tap:     '$$tablerf:brand-discord$$'
      shifted: $$mdi:arrow-up$$
      type:    sym_by_sym
    '&dis_next_server':
      tap:     '$$tablerf:brand-discord$$'
      shifted: $$tabler:world-down$$
      type:    sym_by_sym
    '&dis_prev_server':
      tap:     '$$tablerf:brand-discord$$'
      shifted: $$tabler:world-up$$
      type:    sym_by_sym
    '&dis_next_chan':
      tap:     '$$tablerf:brand-discord$$'
      shifted: $$tabler:row-insert-top$$
      type:    sym_by_sym
    '&dis_prev_chan':
      tap:     '$$tablerf:brand-discord$$'
      shifted: $$tabler:row-insert-bottom$$
      type:    sym_by_sym
    '&dis_next_history':
      tap:     '$$tablerf:brand-discord$$'
      shifted: $$tabler:corner-down-right-double$$
      type:    sym_by_sym
    '&dis_prev_history':
      tap:     '$$tablerf:brand-discord$$'
      shifted: $$tabler:corner-up-left-double$$
      type:    sym_by_sym
    '&dis_next_mention':
      tap:     '$$tablerf:brand-discord$$'
      shifted: $$tabler:at$$
      type:    sym_by_sym
    '&dis_pins':
      tap:     '$$tablerf:brand-discord$$'
      shifted: $$tabler:pinned$$
      type:    sym_by_sym
    '&dis_section_nav':
      tap:     '$$tablerf:brand-discord$$'
      shifted: $$tabler:section-sign$$
      type:    sym_by_sym
  sticky_label: sticky
  toggle_label: toggle
  tap_toggle_label: tap-toggle
  trans_legend:
    t: ▽
    type: trans
  layer_legend_map: {}
  mark_alternate_layer_activators: false
  modifier_fn_map:
    left_ctrl: Ctl
    right_ctrl: Ctl
    left_shift: Sft
    right_shift: Sft
    left_alt: Alt
    right_alt: AltGr
    left_gui: Gui
    right_gui: Gui
    keycode_combiner: '{mods}+{key}'
    mod_combiner: '{mod_1}+{mod_2}'
    special_combinations:
      left_ctrl+left_alt+left_gui+left_shift: Hyper
      left_ctrl+left_alt+left_shift: Meh
  qmk_remove_keycode_prefix:
  - KC_
  qmk_keycode_map:
    XXXXXXX: ''
    'NO': ''
    MINUS: '-'
    MINS: '-'
    EQUAL: '='
    EQL: '='
    LEFT_BRACKET: '['
    LBRC: '['
    RIGHT_BRACKET: ']'
    RBRC: ']'
    BACKSLASH: \
    BSLS: \
    NONUS_HASH: '#'
    NUHS: '#'
    SEMICOLON: ;
    SCLN: ;
    QUOTE: ''''
    QUOT: ''''
    GRAVE: '`'
    GRV: '`'
    COMMA: ','
    COMM: ','
    DOT: .
    SLASH: /
    SLSH: /
    TILDE: '~'
    TILD: '~'
    EXCLAIM: '!'
    EXLM: '!'
    AT: '@'
    HASH: '#'
    DOLLAR: $
    DLR: $
    PERCENT: '%'
    PERC: '%'
    CIRCUMFLEX: ^
    CIRC: ^
    AMPERSAND: '&'
    AMPR: '&'
    ASTERISK: '*'
    ASTR: '*'
    LEFT_PAREN: (
    LPRN: (
    RIGHT_PAREN: )
    RPRN: )
    UNDERSCORE: _
    UNDS: _
    PLUS: +
    LEFT_CURLY_BRACE: '{'
    LCBR: '{'
    RIGHT_CURLY_BRACE: '}'
    RCBR: '}'
    PIPE: '|'
    COLON: ':'
    COLN: ':'
    DOUBLE_QUOTE: '"'
    DQUO: '"'
    DQT: '"'
    LEFT_ANGLE_BRACKET: <
    LABK: <
    LT: <
    RIGHT_ANGLE_BRACKET: '>'
    RABK: '>'
    GT: '>'
    QUESTION: '?'
    QUES: '?'
  zmk_remove_keycode_prefix: [DE_]
  zmk_keycode_map:
    DE_EXCLAMATION: '!'
    DE_EXCL: '!'
    DE_AT_SIGN: '@'
    DE_AT: '@'
    DE_HASH: '#'
    DE_POUND: '#'
    DE_DOLLAR: $
    DE_DLLR: $
    DE_PERCENT: '%'
    DE_PRCNT: '%'
    DE_CARET: ^
    DE_AMPERSAND: '&'
    DE_AMPS: '&'
    DE_ASTERISK: '*'
    DE_ASTRK: '*'
    DE_STAR: '*'
    DE_LEFT_PARENTHESIS: (
    DE_LPAR: (
    DE_RIGHT_PARENTHESIS: )
    DE_RPAR: )
    DE_EQUAL: '='
    DE_PLUS: +
    DE_MINUS: '-'
    DE_UNDERSCORE: _
    DE_UNDER: _
    DE_SLASH: /
    DE_FSLH: /
    DE_QUESTION: '?'
    DE_QMARK: '?'
    DE_BACKSLASH: \
    DE_BSLH: \
    DE_PIPE: '|'
    DE_NON_US_BACKSLASH: \
    DE_PIPE2: '|'
    DE_NON_US_BSLH: '|'
    DE_SEMICOLON: ;
    DE_SEMI: ;
    DE_COLON: ':'
    DE_SINGLE_QUOTE: ''''
    DE_SQT: ''''
    DE_APOSTROPHE: ''''
    DE_APOS: ''''
    DE_DOUBLE_QUOTES: '"'
    DE_DQT: '"'
    DE_COMMA: ','
    DE_LESS_THAN: <
    DE_LT: <
    DE_PERIOD: .
    DE_DOT: .
    DE_GREATER_THAN: '>'
    DE_GT: '>'
    DE_LEFT_BRACKET: '['
    DE_LBKT: '['
    DE_LEFT_BRACE: '{'
    DE_LBRC: '{'
    DE_RIGHT_BRACKET: ']'
    DE_RBKT: ']'
    DE_RIGHT_BRACE: '}'
    DE_RBRC: '}'
    DE_GRAVE: '`'
    DE_TILDE: '~'
    DE_NON_US_HASH: '#'
    DE_NUHS: '#'
    DE_TILDE2: '~'
    C_PP: $$mdi:play-pause$$
    C_NEXT: $$mdi:skip-forward$$
    C_PREV: $$mdi:skip-backward$$
    C_MUTE: $$mdi:volume-mute$$
    C_VOL_UP: $$mdi:volume-plus$$
    C_VOL_DN: $$mdi:volume-minus$$
    C_BRI_UP: $$tabler:brightness-up$$
    C_BRI_DN: $$tabler:brightness-down$$
    C_POWER: $$mdi:power$$
    C_SLEEP: $$mdi:power-sleep$$
    PAGE_UP: 'PgUp'
    PAGE_DOWN: 'PgDn'
    HOME: 'Home'
    END: 'End'
    ESC: 'Esc'
    GLOBE: $$tabler:world$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE: $$mdi:backspace-outline$$
    BSPC: $$mdi:backspace-outlines$$
    DELETE: $$mdi:backspace-reverse-outline$$
    C_PP: $$mdi:play-pause$$
    UP: $$mdi:arrow-up$$
    DOWN: $$mdi:arrow-down$$
    LEFT: $$mdi:arrow-left$$
    RIGHT: $$mdi:arrow-right$$
    UP: $$mdi:arrow-up$$
    DOWN: $$mdi:arrow-down$$
    LEFT: $$mdi:arrow-left$$
    RIGHT: $$mdi:arrow-right$$
    RETURN: ⮐
    ENTER: ⮐
    KP_NUMLOCK: Numlock
    TAB: $$mdi:keyboard-tab$$
    LEFT_GUI: $$mdi:apple-keyboard-command$$
    LGUI: $$mdi:apple-keyboard-command$$
    RIGHT_GUI: $$mdi:apple-keyboard-command$$
    RGUI: $$mdi:apple-keyboard-command$$
    LEFT_ALT: $$mdi:apple-keyboard-option$$
    LALT: $$mdi:apple-keyboard-option$$
    RIGHT_ALT: $$mdi:apple-keyboard-option$$
    RALT: $$mdi:apple-keyboard-option$$
    LEFT_SHIFT: $$mdi:apple-keyboard-shift$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    RIGHT_SHIFT: $$mdi:apple-keyboard-shift$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RIGHT_CONTROL: $$mdi:apple-keyboard-control$$
    RCTRL: $$mdi:apple-keyboard-control$$
    LCTRL: $$mdi:apple-keyboard-control$$
    LEFT_CONTROL: $$mdi:apple-keyboard-control$$
    LC(A): 'tmux prefix'    
  zmk_combos: {}
  zmk_preamble: '#define KEYMAP_DRAWER'
  zmk_additional_includes: []
